services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: scraping-backend
    restart: always
    env_file:
      - .env
    command: uvicorn backend.src.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 300s
      timeout: 10s
      retries: 3
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/code
   
  